import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { CANONICAL_SPECTRAL_CHANNELS } from '../constants/consts.js';
import DistantSunLightSource from '../light/DistantSunLightSource.js';
import ControlledCelestialSampleProvider from '../external-celestial-candidates/ControlledCelestialSampleProvider.js';
import ExternalBoundaryRadiance from '../external-boundary-radiance/ExternalBoundaryRadiance.js';
import ExternalCelestialDepthResolver from '../external-celestial-candidates/ExternalCelestialDepthResolver.js';
import { appendRunLog, nowIso, parseRecordDirectory, writeJson, writeText } from './recordWriter.js';

const recordDirectory = parseRecordDirectory(process.argv); const commandPath = resolve('scripts/flat/reconciliation/POC/browser-jobs/browser-command.json'); await appendRunLog(recordDirectory, 'm5ControlledCelestialSamplesContract started.');
const spectral = (value) => Array(15).fill(value); const directions = { sun: [0, 0, 1], dimStar: unit([0.2, 0, 1]), brightStar: unit([-0.2, 0, 1]), brightBody: unit([0.4, 0, 1]), overlap: unit([0.6, 0, 1]), empty: [0, 1, 0] };
const controlled = new ControlledCelestialSampleProvider({ samples: [
    sample('dim-star', 'star', directions.dimStar, 'infinite', null, false, 0.0002, spectral(0.01)), sample('bright-star', 'star', directions.brightStar, 'infinite', null, false, 0.0003, spectral(1)), sample('bright-planet', 'planet', directions.brightBody, 'finite', 500000, true, 0.004, spectral(3)),
    sample('star-behind-moon', 'star', directions.overlap, 'infinite', null, false, 0.0002, spectral(5)), sample('controlled-moon', 'moon', directions.overlap, 'finite', 384000, true, 0.0045, spectral(2)), sample('star-behind-sun', 'star', directions.sun, 'infinite', null, false, 0.0002, spectral(9)),
] });
const sunSource = new DistantSunLightSource({ directionToLight: directions.sun, spectralChannels: CANONICAL_SPECTRAL_CHANNELS, angularRadiusRadians: 0.00465 }); const sunProvider = sunSource.createVisibleBodyCandidateProvider();
const times = { solarNoon: '2024-06-22T20:00:00.000Z', sunset: '2024-06-23T03:30:00.000Z', postSunset: '2024-06-23T05:00:00.000Z' };
const rayCase = (id, timeBasis, direction, includeSun = false) => { const request = boundaryRequest(direction); const candidates = [...controlled.sample({ cameraRay: request.cameraRay }), ...(includeSun ? [sunProvider.sample({ cameraRay: request.cameraRay })] : [])]; return { id, timeBasis, timeIso: times[timeBasis], candidates, request }; };
const cases = [
    rayCase('solar-noon-dim-star', 'solarNoon', directions.dimStar), rayCase('solar-noon-bright-body', 'solarNoon', directions.brightBody), rayCase('solar-noon-sun-masks-star', 'solarNoon', directions.sun, true), rayCase('solar-noon-empty', 'solarNoon', directions.empty),
    rayCase('sunset-dim-star', 'sunset', directions.dimStar), rayCase('sunset-bright-star', 'sunset', directions.brightStar), rayCase('sunset-bright-body', 'sunset', directions.brightBody), rayCase('sunset-empty', 'sunset', directions.empty),
    rayCase('post-sunset-dim-star', 'postSunset', directions.dimStar), rayCase('post-sunset-bright-star', 'postSunset', directions.brightStar), rayCase('post-sunset-moon-masks-star', 'postSunset', directions.overlap), rayCase('post-sunset-empty', 'postSunset', directions.empty),
];
const samples = cases.map(runCase); const command = { id: `m5-controlled-celestial-${Date.now()}`, label: 'm5-controlled-celestial-samples-parity', page: 'index.html', entrypoint: 'runReconciliationShaderJob', artifactRunDirectory: resolve(recordDirectory), status: 'pending', createdAt: new Date().toISOString(), payload: { jobType: 'external-celestial-depth-parity', cases } }; await writeFile(commandPath, `${JSON.stringify(command, null, 2)}\n`, 'utf8'); const latest = await wait(command.id); const browser = latest?.result?.diagnostics?.scene;
const byId = Object.fromEntries(cases.map((entry, index) => [entry.id, samples[index]])); const criteria = [
    criterion('synthetic-provider-provenance', cases.every((entry) => entry.candidates.filter((candidate) => candidate.bodyId !== 'distant-sun').every((candidate) => candidate.provenance.synthetic === true))), criterion('three-time-fixtures', new Set(cases.map((entry) => entry.timeBasis)).size === 3), criterion('each-time-has-dim-bright-empty', Object.keys(times).every((basis) => cases.some((entry) => entry.timeBasis === basis && entry.id.includes('dim-star')) && cases.some((entry) => entry.timeBasis === basis && entry.id.includes('bright')) && cases.some((entry) => entry.timeBasis === basis && entry.id.includes('empty')))),
    criterion('dim-and-bright-radiance-distinct', byId['sunset-dim-star'].celestialRadiance[0] < byId['sunset-bright-star'].celestialRadiance[0]), criterion('bright-planet-finite-opaque', byId['sunset-bright-body'].bodyId === 'bright-planet'), criterion('empty-rays-no-body', ['solar-noon-empty', 'sunset-empty', 'post-sunset-empty'].every((id) => byId[id].state === 'no-body')), criterion('moon-masks-star', byId['post-sunset-moon-masks-star'].bodyId === 'controlled-moon' && byId['post-sunset-moon-masks-star'].celestialRadiance[0] === 2), criterion('source-owned-sun-masks-star', byId['solar-noon-sun-masks-star'].bodyId === 'distant-sun' && byId['solar-noon-sun-masks-star'].celestialRadiance[0] !== 9),
    criterion('no-display-or-background-fields', !JSON.stringify({ cases, samples }).match(/backgroundColor|displayRgb|sceneRgb|capturedSceneColor/)), criterion('browser-accepted', latest?.status === 'accepted'), criterion('browser-no-three', browser?.threeSceneCreated === false), criterion('cpu-browser-identical', JSON.stringify(browser?.samples) === JSON.stringify(samples)),
]; const status = criteria.every((entry) => entry.status === 'accepted') ? 'accepted' : 'rejected';
await writeText(recordDirectory, 'state-goal.md', '# State Goal\n\nProve controlled dim stars, bright stars, a finite bright body, empty rays, and overlaps through one celestial boundary path across noon, sunset, and post-sunset fixtures.\n'); await writeJson(recordDirectory, 'inputs.json', { stage: 'phase-3-controlled-celestial-samples', times, cases: cases.map(({ id, timeBasis, timeIso }) => ({ id, timeBasis, timeIso })) }); await writeJson(recordDirectory, 'provenance.json', { providerId: controlled.providerId, syntheticPurpose: 'proof scaffolding only', sourceOwnedSun: 'DistantSunLightSource', externalRuntimeLinks: false }); await writeJson(recordDirectory, 'equations-and-constants.json', { channels: 15, ordering: 'finite distance; then body class sun, opaque disk, star, diffuse; then body id', visibilityStatus: 'unattenuated inputs only; daylight visibility deferred to Phase 4' }); await writeJson(recordDirectory, 'criteria-results.json', { status, criteria }); await writeJson(recordDirectory, 'diagnostics.json', { samples, browser }); await writeJson(recordDirectory, 'command.json', { commands: [{ command: `node scripts/flat/reconciliation/POC/src/runners/m5ControlledCelestialSamplesContract.js --record ${recordDirectory}`, timestamp: nowIso() }] }); await writeJson(recordDirectory, 'result.json', { status, samples, browserStatus: latest?.status }); await writeText(recordDirectory, 'report.md', `# Report\n\nStatus: **${status}**\n\nPhase 3 exercised ${cases.length} controlled rays across three time bases with CPU/browser parity. Atmospheric visibility remains Phase 4.\n`); await appendRunLog(recordDirectory, `m5ControlledCelestialSamplesContract ${status}.`); console.log(JSON.stringify({ status, browserStatus: latest?.status, caseCount: cases.length }));

function sample(bodyId, bodyKind, direction, distanceKind, distanceKm, opaque, angularRadiusRadians, celestialRadiance) { return { bodyId, bodyKind, direction, distanceKind, distanceKm, opaque, angularRadiusRadians, celestialRadiance }; } function unit(v) { const m = Math.hypot(...v); return v.map((x) => x / m); }
function boundaryRequest(direction) { return { cameraRay: { origin: [0, 0, 0], direction }, atmosphereContext: { atmosphereId: 'controlled', geometryId: 'controlled', boundary: { kind: 'already-outside' } }, sceneIntersection: null, diagnosticsEnabled: true }; } function runCase(testCase) { const resolver = new ExternalCelestialDepthResolver(); return new ExternalBoundaryRadiance({ provider: { sample: (request) => resolver.sample({ ...request, candidates: testCase.candidates }) } }).sample(testCase.request); } function criterion(name, value) { return { name, status: value ? 'accepted' : 'rejected' }; }
async function wait(id) { const start = Date.now(); while (Date.now() - start < 120000) { try { const value = JSON.parse(await readFile(resolve('tmp/atmosphere/reconciliation/latest.json'), 'utf8')); if (value?.command?.id === id) return value; } catch (error) { if (error.code !== 'ENOENT') throw error; } await new Promise((done) => setTimeout(done, 750)); } throw new Error('Browser watcher timed out.'); }
