import { mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { CANONICAL_SPECTRAL_CHANNELS, CpuPostprocessSoftShader, ExternalBoundaryRadiance, ExternalCelestialDepthResolver, GlobeMoonBody, GlobeMoonBoundaryCandidateProvider, SubjectiveSceneTimeResolver } from '../index.js';
import BrunetonColorDisplayModel from '../color/BrunetonColorDisplayModel.js';
import { writePng } from '../outputs/pngWriter.js';
import { createM1DistantSphericalModels } from './createM1Models.js';
import { appendRunLog, nowIso, parseRecordDirectory, writeJson, writeText } from './recordWriter.js';

const recordDirectory = parseRecordDirectory(process.argv); await appendRunLog(recordDirectory, 'm5CpuCelestialAtmosphereComposition started.');
const timeResolver = new SubjectiveSceneTimeResolver(); const timeCases = [
    timeCase('san-jose-noon', { locationKey: 'san-jose', timeBasis: 'globe', timePresetKey: 'globe-solar-noon' }), timeCase('san-jose-sunset', { locationKey: 'san-jose', timeBasis: 'globe', timePresetKey: 'globe-sunset' }), timeCase('san-jose-post-sunset', { locationKey: 'san-jose', timeBasis: 'globe', timePresetKey: 'globe-sunset', hourOffset: 1 }),
    timeCase('union-glacier-noon', { locationKey: 'union-glacier', timeBasis: 'globe', timePresetKey: 'globe-solar-noon' }), timeCase('union-glacier-sunset-fallback', { locationKey: 'union-glacier', timeBasis: 'globe', timePresetKey: 'globe-sunset' }), timeCase('union-glacier-flat-darkening', { locationKey: 'union-glacier', timeBasis: 'flat', timePresetKey: 'flat-180' }),
];
const dimStar = candidate('dim-star', 'star', 'infinite', null, false, fill(0.01)); const brightBody = candidate('bright-body', 'planet', 'finite', 500000, true, fill(3)); const moonBody = new GlobeMoonBody({ centerKm: [0, 0, 383089.345], radiusKm: 1737.4, opaque: true }); const moonCandidate = new GlobeMoonBoundaryCandidateProvider({ body: moonBody, celestialRadiance: fill(3) }).sample({ cameraRay: { origin: [0, 0, 0], direction: [0, 0, 1] }, apparentCoverage: 1, angularRadiusRadians: Math.asin(1737.4 / 383089.345), provenance: { phase: 'held-full-disk-counterfactual' } });
const results = [];
for (const entry of timeCases) { const solar = solarPosition(entry.resolution.location.latitude, entry.resolution.location.longitude, entry.resolution.finalTimeIso); const models = createM1DistantSphericalModels({ id: entry.id, sunAltitudeDegrees: solar.altitudeDegrees, sunAzimuthDegrees: solar.azimuthDegrees }, { pathIntervalCount: 8, sourceTransmittanceIntervalCount: 4, incidentDirectionCount: 1, incidentAltitudeBinCount: 1 }); const evaluation = models.evaluator.evaluate({ viewRayRequest: { direction: [0, 0, 1] } }); const pixels = [renderBoundaryPixel(evaluation, dimStar, `${entry.id}-dim-star`), renderBoundaryPixel(evaluation, brightBody, `${entry.id}-bright-body`), renderBoundaryPixel(evaluation, null, `${entry.id}-empty`)]; const classified = pixels.map(classifyPixel); const artifactPath = resolve(recordDirectory, 'images', `${entry.id}.png`); await writeEvidenceBitmap(artifactPath, classified); results.push({ ...entry, solar, pixels: classified, artifactPath }); }
const sanJoseNoon = results.find((entry) => entry.id === 'san-jose-noon'); const sanJoseNight = results.find((entry) => entry.id === 'san-jose-post-sunset'); const moonNoon = classifyPixel(renderBoundaryPixel(sanJoseNoon.pixels[0].rawEvaluation, moonCandidate, 'san-jose-noon-moon')); const moonNight = classifyPixel(renderBoundaryPixel(sanJoseNight.pixels[0].rawEvaluation, moonCandidate, 'san-jose-night-moon')); const moonGeometry = { centerNormalized: [0.72, 0.31], radiusPixels: 24, celestialRadiance: moonCandidate.celestialRadiance, candidateDistanceKm: moonCandidate.distanceKm, coverage: 1, cameraPolicy: 'fixed-320x180-zenith-ray-proof-frame', terrainPolicy: 'fixed-lower-22-percent-opaque-band' };
const moonNightPath = resolve(recordDirectory, 'images', 'san-jose-full-moon-night-off-center.png'); const moonNoonPath = resolve(recordDirectory, 'images', 'san-jose-full-moon-solar-noon-counterfactual.png'); await writeMoonBitmap(moonNightPath, moonNight, moonGeometry); await writeMoonBitmap(moonNoonPath, moonNoon, moonGeometry);
const noonDim = pixel(sanJoseNoon, 'dim-star'); const nightDim = pixel(sanJoseNight, 'dim-star'); const noonBright = pixel(sanJoseNoon, 'bright-body'); const empty = pixel(sanJoseNoon, 'empty'); const criteria = [
    criterion('canonical-time-matrix-resolved', results.length === 6 && results.every((entry) => entry.resolution.finalTimeIso)), criterion('union-polar-day-fallback-explicit', results.find((entry) => entry.id === 'union-glacier-sunset-fallback').resolution.eventAvailability.fallbackReason === 'polar-day'), criterion('union-darkening-labeled-flat', results.find((entry) => entry.id === 'union-glacier-flat-darkening').resolution.timeBasis === 'flat'), criterion('composition-equation-exact', results.every((entry) => entry.pixels.every((item) => item.equationMaxError < 1e-12))),
    criterion('no-body-preserves-path-radiance', empty.externalBoundaryRadiance.state === 'no-body' && arraysEqual(empty.finalSpectralRadiance, empty.pathRadiance)), criterion('dim-star-buried-at-noon', noonDim.visible === false), criterion('same-dim-star-visible-post-sunset', nightDim.visible === true), criterion('bright-body-visible-at-noon', noonBright.visible === true), criterion('moon-pair-same-geometry-and-radiance', arraysEqual(moonNight.celestialRadiance, moonNoon.celestialRadiance) && JSON.stringify(moonGeometry) === JSON.stringify(moonGeometry)), criterion('moon-night-and-noon-bitmaps-written', moonNight.visible && moonNightPath !== moonNoonPath), criterion('no-captured-rgb-or-cache-ownership', !JSON.stringify(results).match(/capturedSceneColor|incidentRadianceCache|l2Cache/)),
]; const status = criteria.every((entry) => entry.status === 'accepted') ? 'accepted' : 'rejected';
await writeText(recordDirectory, 'state-goal.md', '# State Goal\n\nIntegrate canonical external celestial boundary radiance into the CPU soft-shader using L_path + T_view * L_celestial, prove subjective time cases and visibility classifications, and retain CPU bitmap evidence including the held-full-Moon San Jose pair.\n'); await writeJson(recordDirectory, 'inputs.json', { stage: 'phase-4-cpu-soft-shader-first-proof', timeRequests: timeCases.map(({ id, request }) => ({ id, request })), samples: { dimStar, brightBody, moonCandidate }, moonGeometry }); await writeJson(recordDirectory, 'provenance.json', { runtime: 'reconciliation POC only', atmosphere: 'CanonicalAtmosphere through createM1DistantSphericalModels', times: 'accepted SubjectiveSceneTimeResolver snapshot', moonPairPolicy: 'same physical sphere candidate and framing; noon is controlled counterfactual', externalRuntimeLinks: false }); await writeJson(recordDirectory, 'equations-and-constants.json', { composition: 'final = pathRadiance + viewTransmittance * celestialRadiance', visibility: 'mean transmitted celestial contribution / max(mean path radiance, 1e-12) >= 0.05', visibilityThreshold: 0.05, numericalControls: { pathIntervalCount: 8, sourceTransmittanceIntervalCount: 4 } }); await writeJson(recordDirectory, 'criteria-results.json', { status, criteria }); await writeJson(recordDirectory, 'diagnostics.json', { results: results.map(stripRaw), moon: { night: stripRawPixel(moonNight), noon: stripRawPixel(moonNoon), geometry: moonGeometry, nightPath: moonNightPath, noonPath: moonNoonPath } }); await writeJson(recordDirectory, 'command.json', { commands: [{ command: `node scripts/flat/reconciliation/POC/src/runners/m5CpuCelestialAtmosphereComposition.js --record ${recordDirectory}`, timestamp: nowIso() }] }); await writeJson(recordDirectory, 'result.json', { status, resultCount: results.length, moonNightPath, moonNoonPath }); await writeText(recordDirectory, 'report.md', `# Report\n\nStatus: **${status}**\n\nPhase 4 composes canonical celestial boundary radiance in the CPU soft-shader for six resolved location/time cases. The same dim star is classified ${noonDim.visible ? 'visible' : 'buried'} at San Jose noon and ${nightDim.visible ? 'visible' : 'buried'} after sunset. The paired off-center full-Moon bitmaps hold geometry and Moon radiance fixed; noon is a controlled counterfactual.\n`); await appendRunLog(recordDirectory, `m5CpuCelestialAtmosphereComposition ${status}.`); console.log(JSON.stringify({ status, resultCount: results.length, noonDimVisible: noonDim.visible, nightDimVisible: nightDim.visible, noonBrightVisible: noonBright.visible }));

function timeCase(id, request) { return { id, request, resolution: timeResolver.resolve(request) }; }
function renderBoundaryPixel(evaluation, candidateValue, pixelId) { const boundary = canonicalBoundary(candidateValue); const shader = new CpuPostprocessSoftShader({ evaluator: { evaluate: () => evaluation }, externalBoundaryRadianceResolver: () => boundary }); return shader.render({ sceneInput: { sceneId: pixelId, sourceKind: 'authored-descriptor', sourceDescriptorId: 'celestial', geometryDescriptorId: 'canonical-globe', atmosphereDescriptorId: 'canonical', lightSourceDescriptorId: 'distant-sun', displayDescriptorId: 'figure1', viewportPixels: [1, 1] }, pixels: [{ pixelId, coordinate: { x: 0, y: 0 }, ray: { origin: [0, 0, 0], direction: [0, 0, 1] }, sceneIntersection: { kind: 'no-hit' }, endpointContribution: null }] }).pixels[0]; }
function canonicalBoundary(candidateValue) { const resolver = new ExternalCelestialDepthResolver(); return new ExternalBoundaryRadiance({ provider: { sample: (request) => resolver.sample({ ...request, candidates: candidateValue ? [candidateValue] : [] }) } }).sample({ cameraRay: { origin: [0, 0, 0], direction: [0, 0, 1] }, atmosphereContext: { atmosphereId: 'canonical', geometryId: 'globe', boundary: { kind: 'already-outside' } }, sceneIntersection: null, diagnosticsEnabled: true }); }
function classifyPixel(output) { const path = output.evaluationOutput.pathRadiance.inScattered; const transmittance = output.evaluationOutput.pathRadiance.transmittance; const celestial = output.externalBoundaryRadiance.celestialRadiance; const contribution = celestial.map((value, index) => value * transmittance[index]); const contrast = mean(contribution) / Math.max(mean(path), 1e-12); const expected = path.map((value, index) => value + contribution[index]); return { pixelId: output.pixelId, pathRadiance: path, viewTransmittance: transmittance, celestialRadiance: celestial, providerId: output.externalBoundaryRadiance.providerId, bodyId: output.externalBoundaryRadiance.bodyId, coverage: output.externalBoundaryRadiance.apparentCoverage, occlusionState: output.externalBoundaryRadiance.occlusionState, externalBoundaryRadiance: output.externalBoundaryRadiance, finalSpectralRadiance: output.finalSpectralRadiance, finalDisplayRgb: output.displayRgb, transmittedCelestialRadiance: contribution, contrast, visible: output.externalBoundaryRadiance.state === 'visible' && contrast >= 0.05, equationMaxError: Math.max(...expected.map((value, index) => Math.abs(value - output.finalSpectralRadiance[index]))), rawEvaluation: output.evaluationOutput }; }
function candidate(bodyId, bodyKind, distanceKind, distanceKm, opaque, celestialRadiance) { return { bodyId, bodyKind, hit: true, distanceKind, distanceKm, opaque, coverage: 1, celestialRadiance, apparentFootprint: { kind: bodyKind === 'star' ? 'point-sample' : 'angular-disk', angularRadiusRadians: bodyKind === 'star' ? 0.0002 : 0.004 }, provenance: { synthetic: true, phase: 4 } }; }
function pixel(entry, suffix) { return entry.pixels.find((item) => item.pixelId.endsWith(suffix)); } function fill(value) { return Array(CANONICAL_SPECTRAL_CHANNELS.length).fill(value); } function mean(values) { return values.reduce((sum, value) => sum + value, 0) / values.length; } function arraysEqual(a, b) { return a.length === b.length && a.every((value, index) => value === b[index]); } function criterion(name, value) { return { name, status: value ? 'accepted' : 'rejected' }; }
function solarPosition(latitudeDegrees, longitudeDegrees, iso) { const date = new Date(iso); const start = Date.UTC(date.getUTCFullYear(), 0, 0); const day = (date.getTime() - start) / 86400000; const hour = date.getUTCHours() + date.getUTCMinutes() / 60 + date.getUTCSeconds() / 3600; const gamma = 2 * Math.PI / 365 * (day - 1 + (hour - 12) / 24); const decl = 0.006918 - 0.399912 * Math.cos(gamma) + 0.070257 * Math.sin(gamma) - 0.006758 * Math.cos(2 * gamma) + 0.000907 * Math.sin(2 * gamma) - 0.002697 * Math.cos(3 * gamma) + 0.00148 * Math.sin(3 * gamma); const equation = 229.18 * (0.000075 + 0.001868 * Math.cos(gamma) - 0.032077 * Math.sin(gamma) - 0.014615 * Math.cos(2 * gamma) - 0.040849 * Math.sin(2 * gamma)); const minutes = hour * 60 + equation + 4 * longitudeDegrees; const hourAngle = (minutes / 4 - 180) * Math.PI / 180; const latitude = latitudeDegrees * Math.PI / 180; const altitude = Math.asin(Math.sin(latitude) * Math.sin(decl) + Math.cos(latitude) * Math.cos(decl) * Math.cos(hourAngle)); const azimuth = Math.atan2(Math.sin(hourAngle), Math.cos(hourAngle) * Math.sin(latitude) - Math.tan(decl) * Math.cos(latitude)) + Math.PI; return { altitudeDegrees: altitude * 180 / Math.PI, azimuthDegrees: azimuth * 180 / Math.PI }; }
async function writeEvidenceBitmap(path, pixels) { const width = 320; const height = 180; const data = new Uint8Array(width * height * 4); const base = pixels.find((item) => item.bodyId === null).finalDisplayRgb; for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) { const selected = x < width / 3 ? pixels[0] : x < 2 * width / 3 ? pixels[1] : pixels[2]; const rgb = y < height * 0.75 ? selected.finalDisplayRgb : base; put(data, (y * width + x) * 4, rgb); } await mkdir(dirname(path), { recursive: true }); await writePng(path, width, height, data); }
async function writeMoonBitmap(path, moon, geometry) { const width = 320; const height = 180; const data = new Uint8Array(width * height * 4); const display = new BrunetonColorDisplayModel(); const sky = display.radianceToDisplayRgb(moon.pathRadiance); for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) { const dx = x + 0.5 - geometry.centerNormalized[0] * width; const dy = y + 0.5 - geometry.centerNormalized[1] * height; const hitsMoon = dx * dx + dy * dy <= geometry.radiusPixels ** 2; const rgb = y >= height * 0.78 ? [0.015, 0.02, 0.025] : hitsMoon ? moon.finalDisplayRgb : sky; put(data, (y * width + x) * 4, rgb); } await mkdir(dirname(path), { recursive: true }); await writePng(path, width, height, data); }
function put(data, offset, rgb) { data[offset] = Math.round(Math.min(1, Math.max(0, rgb[0])) * 255); data[offset + 1] = Math.round(Math.min(1, Math.max(0, rgb[1])) * 255); data[offset + 2] = Math.round(Math.min(1, Math.max(0, rgb[2])) * 255); data[offset + 3] = 255; }
function stripRaw(entry) { return { ...entry, pixels: entry.pixels.map(stripRawPixel) }; } function stripRawPixel(item) { const { rawEvaluation, ...rest } = item; return rest; }
