import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import ExternalBoundaryRadiance from '../external-boundary-radiance/ExternalBoundaryRadiance.js';
import ExternalCelestialDepthResolver from '../external-celestial-candidates/ExternalCelestialDepthResolver.js';
import GlobeMoonBoundaryCandidateProvider from '../external-celestial-candidates/GlobeMoonBoundaryCandidateProvider.js';
import GlobeMoonBody from '../globe-moon/GlobeMoonBody.js';
import { appendRunLog, nowIso, parseRecordDirectory, writeJson, writeText } from './recordWriter.js';

const recordDirectory = parseRecordDirectory(process.argv); const commandPath = resolve('scripts/flat/reconciliation/POC/browser-jobs/browser-command.json');
const fixturePath = resolve('scripts/flat/reconciliation/POC/src/globe-moon/fixtures/san-jose-2024-06-full-moon-state.json'); const fixture = JSON.parse(await readFile(fixturePath, 'utf8'));
await appendRunLog(recordDirectory, 'm5ExternalCelestialDepthContract started.');
const spectral = (value) => Array(15).fill(value); const moonBody = new GlobeMoonBody({ centerKm: fixture.worldState.moon.positionKm, radiusKm: fixture.worldState.moon.radiusKm, opaque: true });
const moonProvider = new GlobeMoonBoundaryCandidateProvider({ body: moonBody, celestialRadiance: spectral(2) }); const ray = { origin: fixture.observerState.positionKm, direction: normalize(fixture.worldState.moon.positionKm.map((v, i) => v - fixture.observerState.positionKm[i])) };
const moon = moonProvider.sample({ cameraRay: ray, apparentCoverage: 1, angularRadiusRadians: 0.0045, provenance: { fixture: 'san-jose-2024-06-full-moon-state' } });
const moonMiss = moonProvider.sample({ cameraRay: { origin: ray.origin, direction: ray.direction.map((v) => -v) } }); const localMoonProvider = new GlobeMoonBoundaryCandidateProvider({ body: new GlobeMoonBody({ centerKm: [0, 0, 0], radiusKm: 1737.4, opaque: true }), celestialRadiance: spectral(2) }); const moonTangent = localMoonProvider.sample({ cameraRay: { origin: [1737.4, 0, 0], direction: [0, 1, 0] } });
const star = candidate('star', 'star-field', false, 'infinite', null, 1, spectral(7)); const hitStar = { ...star, hit: true }; const sun = candidate('sun', 'sun', true, 'finite', moon.distanceKm + 1000000, 1, spectral(11));
const request = (sceneIntersection = null) => ({ cameraRay: ray, atmosphereContext: { atmosphereId: 'test', geometryId: 'globe', boundary: { kind: 'already-outside' } }, sceneIntersection, diagnosticsEnabled: true });
const cases = [
    { id: 'moon-masks-star', candidates: [hitStar, moon], request: request() },
    { id: 'moon-before-sun', candidates: [sun, moon], request: request() },
    { id: 'nonoverlap-star', candidates: [star], request: request() },
    { id: 'scene-occludes-moon', candidates: [moon], request: request({ kind: 'hit', distanceMeters: 1000 }) },
    { id: 'partial-coverage', candidates: [{ ...moon, coverage: 0.25 }], request: request() },
    { id: 'no-candidate', candidates: [], request: request() },
    { id: 'deterministic-tie', candidates: [{ ...sun, bodyId: 'z-body', distanceKm: moon.distanceKm }, { ...sun, bodyId: 'a-body', distanceKm: moon.distanceKm }], request: request() },
];
const samples = cases.map(runCase); const malformedRejected = reject(() => runCase({ candidates: [{ ...moon, celestialRadiance: [1] }], request: request() })); const duplicateRejected = reject(() => runCase({ candidates: [moon, moon], request: request() })); const negativeRejected = reject(() => runCase({ candidates: [{ ...moon, distanceKm: -1 }], request: request() }));
const command = { id: `m5-external-celestial-depth-${Date.now()}`, label: 'm5-external-celestial-depth-parity', page: 'index.html', entrypoint: 'runReconciliationShaderJob', artifactRunDirectory: resolve(recordDirectory), status: 'pending', createdAt: new Date().toISOString(), payload: { jobType: 'external-celestial-depth-parity', cases } };
await writeFile(commandPath, `${JSON.stringify(command, null, 2)}\n`, 'utf8'); const latest = await wait(command.id); const browser = latest?.result?.diagnostics?.scene;
const criteria = [
    criterion('moon-candidate-is-finite', moon.hit && moon.distanceKind === 'finite' && moon.distanceKm > 0), criterion('moon-provider-hit-miss-tangent', !moonMiss.hit && moonTangent.hit && moonTangent.distanceKm === 0), criterion('moon-masks-infinite-star', samples[0].bodyId === 'moon' && samples[0].celestialRadiance[0] === 2), criterion('moon-precedes-far-sun', samples[1].bodyId === 'moon' && samples[1].celestialRadiance[0] === 2),
    criterion('nonoverlap-is-no-body', samples[2].state === 'no-body'), criterion('near-scene-hit-occludes', samples[3].state === 'occluded' && samples[3].celestialRadiance.every((v) => v === 0)), criterion('partial-coverage-resolved', samples[4].celestialRadiance[0] === 0.5), criterion('empty-is-no-body', samples[5].state === 'no-body'),
    criterion('deterministic-body-id-tie-break', samples[6].bodyId === 'a-body'), criterion('malformed-spectral-rejected', malformedRejected), criterion('duplicate-id-rejected', duplicateRejected), criterion('negative-distance-rejected', negativeRejected), criterion('browser-runner-accepted', latest?.status === 'accepted'), criterion('browser-created-no-three-scene', browser?.threeSceneCreated === false), criterion('cpu-browser-packets-identical', JSON.stringify(browser?.samples) === JSON.stringify(samples)),
]; const status = criteria.every((c) => c.status === 'accepted') ? 'accepted' : 'rejected';
await writeText(recordDirectory, 'state-goal.md', '# State Goal\n\nProve finite external-body candidates, deterministic depth/masking, scene occlusion, coverage resolution, and identical canonical CPU/browser boundary packets.\n'); await writeJson(recordDirectory, 'inputs.json', { stage: 'G2-external-celestial-depth', fixturePath, cases: cases.map((c) => c.id) }); await writeJson(recordDirectory, 'provenance.json', { fixture: fixture.provenance, implementation: 'local POC only' }); await writeJson(recordDirectory, 'equations-and-constants.json', { ordering: 'finite ascending, infinite last, bodyId tie-break', coverage: 'front-to-back: weight=remaining*coverage', channels: 15 }); await writeJson(recordDirectory, 'criteria-results.json', { status, criteria }); await writeJson(recordDirectory, 'diagnostics.json', { samples, browser }); await writeJson(recordDirectory, 'command.json', { commands: [{ command: `node scripts/flat/reconciliation/POC/src/runners/m5ExternalCelestialDepthContract.js --record ${recordDirectory}`, timestamp: nowIso() }] }); await writeJson(recordDirectory, 'result.json', { status, samples, browserStatus: latest?.status }); await writeText(recordDirectory, 'report.md', `# Report\n\nStatus: **${status}**\n\nG2 resolved ${samples.length} CPU cases and browser parity without a Three scene or bitmap render.\n`); await appendRunLog(recordDirectory, `m5ExternalCelestialDepthContract ${status}.`); console.log(JSON.stringify({ status, browserStatus: latest?.status, caseCount: samples.length }));

function runCase(testCase) { const resolver = new ExternalCelestialDepthResolver(); return new ExternalBoundaryRadiance({ provider: { sample: (normalized) => resolver.sample({ ...normalized, candidates: testCase.candidates }) } }).sample(testCase.request); }
function candidate(bodyId, bodyKind, hit, distanceKind, distanceKm, coverage, celestialRadiance) { return { schemaVersion: 1, bodyId, bodyKind, hit, distanceKind, distanceKm, opaque: true, coverage, celestialRadiance, apparentFootprint: { kind: 'point-sample', angularRadiusRadians: null }, provenance: { synthetic: true } }; }
function reject(fn) { try { fn(); return false; } catch { return true; } } function criterion(name, ok) { return { name, status: ok ? 'accepted' : 'rejected' }; } function normalize(v) { const m = Math.hypot(...v); return v.map((x) => x / m); }
async function wait(id) { const start = Date.now(); while (Date.now() - start < 120000) { try { const value = JSON.parse(await readFile(resolve('tmp/atmosphere/reconciliation/latest.json'), 'utf8')); if (value?.command?.id === id) return value; } catch (error) { if (error.code !== 'ENOENT') throw error; } await new Promise((done) => setTimeout(done, 750)); } throw new Error('Browser watcher timed out.'); }
