import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { appendRunLog, nowIso, parseRecordDirectory, writeJson, writeText } from './recordWriter.js';

const recordDirectory = parseRecordDirectory(process.argv); const sourceRecord = resolve('tmp/atmosphere/reconciliation/012-m5-cpu-celestial-atmosphere-composition'); const diagnostics = JSON.parse(await readFile(resolve(sourceRecord, 'diagnostics.json'), 'utf8')); const commandPath = resolve('scripts/flat/reconciliation/POC/browser-jobs/browser-command.json'); await appendRunLog(recordDirectory, 'm5GpuCelestialBrowserParity started.');
const allPixels = diagnostics.results.flatMap((entry) => entry.pixels.map((pixel) => ({ id: pixel.pixelId, pathRadiance: pixel.pathRadiance, viewTransmittance: pixel.viewTransmittance, celestialRadiance: pixel.celestialRadiance, finalSpectralRadiance: pixel.finalSpectralRadiance })));
const nightMoon = diagnostics.moon.night; const noonMoon = diagnostics.moon.noon; const nightDim = findPixel(diagnostics, 'san-jose-post-sunset', 'dim-star'); const noonDim = findPixel(diagnostics, 'san-jose-noon', 'dim-star');
const payload = { jobType: 'celestial-gpu-parity', viewportPixels: [640, 360], packetCases: allPixels, night: { pathRgb: bands(nightMoon.pathRadiance), moon: packed(nightMoon), dimStar: packed(nightDim) }, noon: { pathRgb: bands(noonMoon.pathRadiance), moon: packed(noonMoon), dimStar: packed(noonDim) } };
const command = { id: `m5-gpu-celestial-${Date.now()}`, label: 'm5-gpu-celestial-browser-parity', page: 'index.html', entrypoint: 'runReconciliationShaderJob', artifactRunDirectory: resolve(recordDirectory), status: 'pending', createdAt: new Date().toISOString(), payload }; await writeFile(commandPath, `${JSON.stringify(command, null, 2)}\n`, 'utf8'); const latest = await wait(command.id); const scene = latest?.result?.diagnostics?.scene; const selected = latest?.result?.selectedPixels ?? [];
const expectedNight = expectedBytes(payload.night.moon); const expectedNoon = expectedBytes(payload.noon.moon); const nightError = pixelError(selected[0]?.rgba, expectedNight); const noonError = pixelError(selected[1]?.rgba, expectedNoon); const criteria = [
    criterion('phase-4-source-record-accepted', JSON.parse(await readFile(resolve(sourceRecord, 'criteria-results.json'), 'utf8')).status === 'accepted'), criterion('browser-runner-accepted', latest?.status === 'accepted'), criterion('real-three-scene-created', scene?.threeSceneCreated === true), criterion('physical-moon-mesh-and-star-depth-policy', latest?.result?.criteriaResults?.some((entry) => entry.criterionId === 'physical-moon-and-stars-depth-tested' && entry.status === 'pass')), criterion('all-cpu-browser-spectral-packets-match', scene?.packetCases?.length === allPixels.length && scene.packetCases.every((entry) => entry.maxError < 1e-12)), criterion('matched-night-noon-geometry', scene?.identicalGeometry === true), criterion('gpu-night-moon-pixel-within-tolerance', nightError <= 2 / 255), criterion('gpu-noon-moon-pixel-within-tolerance', noonError <= 2 / 255), criterion('paired-browser-images-retained', scene?.captures?.night && scene?.captures?.noon), criterion('packing-policy-explicit', scene?.packingPolicy === '15-channel-authoritative-three-band-linear-raster-bridge'),
]; const status = criteria.every((entry) => entry.status === 'accepted') ? 'accepted' : 'rejected';
await writeText(recordDirectory, 'state-goal.md', '# State Goal\n\nPort the accepted Phase 4 celestial boundary packets into a browser GPU/Three path, preserve the 15-channel equation for packet parity, render a named three-band bridge, and retain matched real Three San Jose Moon scenes.\n'); await writeJson(recordDirectory, 'inputs.json', { stage: 'phase-5-gpu-browser-parity', sourceRecord, viewportPixels: payload.viewportPixels, packetCaseCount: allPixels.length }); await writeJson(recordDirectory, 'provenance.json', { cpuSource: sourceRecord, runtime: 'reconciliation POC browser runner', externalRuntimeLinks: false, celestialRgbPolicy: 'material shader uniforms derived from boundary packet; not captured scene RGB' }); await writeJson(recordDirectory, 'equations-and-constants.json', { authoritative: '15-channel final = path + transmittance * celestial', gpuPacking: 'R=mean(channels 8..14), G=mean(4..8), B=mean(0..4)', pixelTolerance: 2 / 255 }); await writeJson(recordDirectory, 'criteria-results.json', { status, criteria }); await writeJson(recordDirectory, 'diagnostics.json', { browser: scene, selectedPixels: selected, expected: { night: expectedNight, noon: expectedNoon }, errors: { nightError, noonError } }); await writeJson(recordDirectory, 'command.json', { commands: [{ command: `node scripts/flat/reconciliation/POC/src/runners/m5GpuCelestialBrowserParity.js --record ${recordDirectory}`, timestamp: nowIso() }] }); await writeJson(recordDirectory, 'result.json', { status, browserStatus: latest?.status, packetCaseCount: allPixels.length, nightError, noonError, images: ['images/san-jose-full-moon-night-three.png', 'images/san-jose-full-moon-noon-three.png'] }); await writeText(recordDirectory, 'report.md', `# Report\n\nStatus: **${status}**\n\nPhase 5 retained ${allPixels.length} exact 15-channel CPU/browser packet comparisons and rendered matched depth-tested Three Moon/star scenes through the named three-band GPU bridge. Night/noon Moon pixel errors were ${nightError} and ${noonError}.\n`); await appendRunLog(recordDirectory, `m5GpuCelestialBrowserParity ${status}.`); console.log(JSON.stringify({ status, browserStatus: latest?.status, packetCaseCount: allPixels.length, nightError, noonError }));

function findPixel(root, resultId, suffix) { return root.results.find((entry) => entry.id === resultId).pixels.find((entry) => entry.pixelId.endsWith(suffix)); } function average(values) { return values.reduce((sum, value) => sum + value, 0) / values.length; } function bands(value) { return [average(value.slice(8)), average(value.slice(4, 9)), average(value.slice(0, 5))]; } function packed(pixel) { return { pathRgb: bands(pixel.pathRadiance), transmittanceRgb: bands(pixel.viewTransmittance), celestialRgb: bands(pixel.celestialRadiance) }; } function expectedBytes(packet) { return packet.pathRgb.map((value, index) => Math.round(Math.min(1, Math.max(0, value + packet.transmittanceRgb[index] * packet.celestialRgb[index])) * 255)); } function pixelError(actual, expected) { if (!actual) return Infinity; return Math.max(...expected.map((value, index) => Math.abs(actual[index] - value) / 255)); } function criterion(name, value) { return { name, status: value ? 'accepted' : 'rejected' }; }
async function wait(id) { const start = Date.now(); while (Date.now() - start < 120000) { try { const value = JSON.parse(await readFile(resolve('tmp/atmosphere/reconciliation/latest.json'), 'utf8')); if (value?.command?.id === id) return value; } catch (error) { if (error.code !== 'ENOENT') throw error; } await new Promise((done) => setTimeout(done, 750)); } throw new Error('Browser watcher timed out.'); }
