import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { CANONICAL_SPECTRAL_CHANNELS } from '../constants/consts.js';
import DistantSunLightSource from '../light/DistantSunLightSource.js';
import LocalSunLightSource from '../light/LocalSunLightSource.js';
import ExternalBoundaryRadiance from '../external-boundary-radiance/ExternalBoundaryRadiance.js';
import ExternalCelestialDepthResolver from '../external-celestial-candidates/ExternalCelestialDepthResolver.js';
import { appendRunLog, nowIso, parseRecordDirectory, writeJson, writeText } from './recordWriter.js';

const recordDirectory = parseRecordDirectory(process.argv); const commandPath = resolve('scripts/flat/reconciliation/POC/browser-jobs/browser-command.json'); await appendRunLog(recordDirectory, 'm5SourceOwnedSunDiskContract started.');
const angularRadius = 0.00465; const distantSource = new DistantSunLightSource({ directionToLight: [0, 0, 1], spectralChannels: CANONICAL_SPECTRAL_CHANNELS, angularRadiusRadians: angularRadius });
const localSource = new LocalSunLightSource({ sourceKey: 'local-sun', spectralChannels: CANONICAL_SPECTRAL_CHANNELS, referenceDistanceMeters: 100000, referenceSpectralIncidentScale: 1, radiusMeters: 1000, distanceFalloff: true });
const distantProvider = distantSource.createVisibleBodyCandidateProvider(); const localProvider = localSource.createVisibleBodyCandidateProvider(); const origin = [0, 0, 0]; const pixelRadius = 0.001;
const distantCenter = distantProvider.sample({ cameraRay: { origin, direction: [0, 0, 1] } }); const distantEdge = distantProvider.sample({ cameraRay: { origin, direction: directionAt(angularRadius) }, pixelAngularRadiusRadians: pixelRadius }); const distantMiss = distantProvider.sample({ cameraRay: { origin, direction: directionAt(0.02) }, pixelAngularRadiusRadians: pixelRadius });
const localPosition = [0, 0, 100000]; const localAngularRadius = Math.asin(0.01); const localCenter = localProvider.sample({ cameraRay: { origin, direction: [0, 0, 1] }, sourcePositionMeters: localPosition }); const localEdge = localProvider.sample({ cameraRay: { origin, direction: directionAt(localAngularRadius) }, sourcePositionMeters: localPosition, pixelAngularRadiusRadians: pixelRadius }); const localMiss = localProvider.sample({ cameraRay: { origin, direction: directionAt(0.03) }, sourcePositionMeters: localPosition, pixelAngularRadiusRadians: pixelRadius });
const moonInFront = { ...localCenter, bodyId: 'moon', bodyKind: 'globe-moon', distanceKm: localCenter.distanceKm / 2, celestialRadiance: Array(15).fill(0.25), provenance: { syntheticOrderingFixture: true } };
const request = (direction, sceneIntersection = null) => ({ cameraRay: { origin, direction }, atmosphereContext: { atmosphereId: 'test', geometryId: 'controlled', boundary: { kind: 'already-outside' } }, sceneIntersection, diagnosticsEnabled: true });
const cases = [
    { id: 'distant-center', candidates: [distantCenter], request: request([0, 0, 1]) }, { id: 'distant-edge-coverage', candidates: [distantEdge], request: request(directionAt(angularRadius)) }, { id: 'distant-miss', candidates: [distantMiss], request: request(directionAt(0.02)) },
    { id: 'distant-scene-occluded', candidates: [distantCenter], request: request([0, 0, 1], { kind: 'hit', distanceMeters: 10 }) }, { id: 'local-center', candidates: [localCenter], request: request([0, 0, 1]) }, { id: 'local-edge-coverage', candidates: [localEdge], request: request(directionAt(localAngularRadius)) }, { id: 'local-miss', candidates: [localMiss], request: request(directionAt(0.03)) },
    { id: 'moon-before-local-sun', candidates: [localCenter, moonInFront], request: request([0, 0, 1]) }, { id: 'local-scene-occluded', candidates: [localCenter], request: request([0, 0, 1], { kind: 'hit', distanceMeters: 5 }) },
];
const samples = cases.map(runCase); const command = { id: `m5-source-owned-sun-${Date.now()}`, label: 'm5-source-owned-sun-disk-parity', page: 'index.html', entrypoint: 'runReconciliationShaderJob', artifactRunDirectory: resolve(recordDirectory), status: 'pending', createdAt: new Date().toISOString(), payload: { jobType: 'external-celestial-depth-parity', cases } }; await writeFile(commandPath, `${JSON.stringify(command, null, 2)}\n`, 'utf8'); const latest = await wait(command.id); const browser = latest?.result?.diagnostics?.scene;
const criteria = [
    criterion('distant-source-owns-provider', distantSource.createVisibleBodyCandidateProvider().source === distantSource), criterion('local-source-owns-provider', localSource.createVisibleBodyCandidateProvider().source === localSource), criterion('distant-center-visible-infinite', samples[0].state === 'visible' && distantCenter.distanceKind === 'infinite' && distantCenter.coverage === 1), criterion('distant-edge-antialiased', distantEdge.coverage > 0 && distantEdge.coverage < 1), criterion('distant-miss-no-body', samples[2].state === 'no-body'), criterion('distant-scene-occluded', samples[3].state === 'occluded'),
    criterion('local-center-visible-finite-sphere', samples[4].state === 'visible' && localCenter.distanceKind === 'finite' && localCenter.provenance.exactSphereHit === true), criterion('local-edge-antialiased', localEdge.coverage > 0 && localEdge.coverage < 1), criterion('local-miss-no-body', samples[6].state === 'no-body'), criterion('moon-masks-local-sun', samples[7].bodyId === 'moon' && samples[7].celestialRadiance[0] === 0.25), criterion('local-scene-occluded', samples[8].state === 'occluded'),
    criterion('physical-spectral-calibration', [distantCenter, localCenter].every((candidate) => candidate.provenance.radianceCalibration.includes('projected-solid-angle') && candidate.celestialRadiance.length === 15 && candidate.celestialRadiance.every((value) => value > 0))), criterion('diagnostics-carry-source-facts', samples[0].diagnostics[0].contributors[0].provenance.sourceOwner === 'DistantSunLightSource' && samples[4].diagnostics[0].contributors[0].provenance.sourceOwner === 'LocalSunLightSource'), criterion('browser-runner-accepted', latest?.status === 'accepted'), criterion('browser-no-three', browser?.threeSceneCreated === false), criterion('cpu-browser-identical', JSON.stringify(browser?.samples) === JSON.stringify(samples)),
]; const status = criteria.every((entry) => entry.status === 'accepted') ? 'accepted' : 'rejected';
await writeText(recordDirectory, 'state-goal.md', '# State Goal\n\nProve source-owned distant and local Sun disks through the accepted celestial-candidate, depth, and external-boundary contracts.\n'); await writeJson(recordDirectory, 'inputs.json', { stage: 'phase-2-source-owned-sun-disk', cases: cases.map((entry) => entry.id), distant: distantSource.configuration, local: localSource.configuration }); await writeJson(recordDirectory, 'provenance.json', { implementationRoot: 'scripts/flat/reconciliation/POC', sourceOwnership: ['DistantSunLightSource', 'LocalSunLightSource'], externalRuntimeLinks: false }); await writeJson(recordDirectory, 'equations-and-constants.json', { distantHit: 'angle(ray,sunDirection) within angularRadius plus pixel footprint', localHit: 'ray/sphere with angular pixel footprint', radiance: 'incidentRadiance / (pi * sin(angularRadius)^2)', coverage: 'linear transition across pixel angular radius' }); await writeJson(recordDirectory, 'criteria-results.json', { status, criteria }); await writeJson(recordDirectory, 'diagnostics.json', { candidates: { distantCenter, distantEdge, distantMiss, localCenter, localEdge, localMiss }, samples, browser }); await writeJson(recordDirectory, 'command.json', { commands: [{ command: `node scripts/flat/reconciliation/POC/src/runners/m5SourceOwnedSunDiskContract.js --record ${recordDirectory}`, timestamp: nowIso() }] }); await writeJson(recordDirectory, 'result.json', { status, samples, browserStatus: latest?.status }); await writeText(recordDirectory, 'report.md', `# Report\n\nStatus: **${status}**\n\nPhase 2 exercised ${cases.length} source-owned Sun-disk cases with CPU/browser packet parity and no Three scene or bitmap.\n`); await appendRunLog(recordDirectory, `m5SourceOwnedSunDiskContract ${status}.`); console.log(JSON.stringify({ status, browserStatus: latest?.status, caseCount: cases.length }));

function runCase(testCase) { const resolver = new ExternalCelestialDepthResolver(); return new ExternalBoundaryRadiance({ provider: { sample: (normalized) => resolver.sample({ ...normalized, candidates: testCase.candidates }) } }).sample(testCase.request); }
function directionAt(angle) { return [Math.sin(angle), 0, Math.cos(angle)]; } function criterion(name, value) { return { name, status: value ? 'accepted' : 'rejected' }; }
async function wait(id) { const start = Date.now(); while (Date.now() - start < 120000) { try { const value = JSON.parse(await readFile(resolve('tmp/atmosphere/reconciliation/latest.json'), 'utf8')); if (value?.command?.id === id) return value; } catch (error) { if (error.code !== 'ENOENT') throw error; } await new Promise((done) => setTimeout(done, 750)); } throw new Error('Browser watcher timed out.'); }
